### PR TITLE
Fix Issue #22

### PR DESCRIPTION
**Pull request by lepigocher**

### CODE REVIEW

**Comment by ohine** [comment]
Thanks for submitting the pull request @lepigocher! Do you have time to clean it up a bit? It might be easier to submit a new PR. I would like to keep all references and assemblies out of git and let nuget restore them all on the first load of the project locally. This will keep our repo size down quite a bit. If it's not too much trouble, could you resubmit this and only add the code files. Skip all the configs, assemblies, and packages. I'm going to see about getting the gitignore file updated so these files aren't added by default. On my workstation I've excluded them. Sorry about that. 

If you don't have time to redo the PR, I can cherry pick just the update to the data query. Let me know how you'd like to proceed. Thanks again! I love seeing pull requests come in for the new control panel :+1:

**Comment by lepigocher** [comment]
Hi Oliver, I tried a lot of things with this FU#@NG Git (Yes I hate all of this Tools) and lost everything. If you have time we could try a team viewer session.

**Comment by ohine** [comment]
I would be happy to help. Ping me on FB and we can setup a time that's good for both of us.

**Comment by lepigocher** [comment]
I Oliver, Sorry but it's a little bit late because I started my summer holidays! :-) I will be back in august the 16th. I can connect with my phone for email but I have to avoid download.

**Comment by ohine** [comment]
Thanks for reporting the issue and doing the fix. Hopefully you had a great holiday! I just manually merged the commit and the fix will be in the v0.1.3 release I'm working on finalizing now. I figured this would be the quickest way to get things implemented. Hopefully the next fix will go smoother, I've updated the git ignore file to prevent the temp files from getting added to the commit.

**Comment by lepigocher** [comment]
Hi Oliver, thanks for the manual merge/commit and sorry for the extra works! I will do a better work the next time! :-)

**Pull request closed without merging**
